First proposal for core data structures [RFC]
vizzTools/vizzToolsCore pull request #2
Opened 2020-10-20 17:09 UTC by edwardpmorris

First idea for some of the main Classes. Did not make the JSON schema yet (fix the structure and rules for the objects); waiting on some feedback. Once that is ready will convert to Python code.

2020-10-20 17:33 UTC, aagm requested changes
Don't add vscode cconfig files. The repo should not contain ide config files as they are a programmer specific choice. Further explanation about this: TG.

2020-10-20 18:24 UTC, aagm requested changes

2020-10-20 18:24 UTC, aagm commented on README.md
> +> DISCUSS: I favor human readable identifier, but how to ensure these are unique? We could use UUIDs and/or include another `identifier`?.
In rw we use uuid  and  a slug to cover both needs (uuid for machine uniq identifier) and a unique slug for human readable (id?)

2020-10-20 18:24 UTC, aagm commented on README.md
> +A list of Provider configuration objects, which follow the structure of `pygeoapi` [resources.providers configuration](https://docs.pygeoapi.io/en/latest/configuration.html#resources). The aim of pro
My big concern here is that we are trying to reinvent the wheel, why not use geoapi directly?

2020-10-20 18:24 UTC, aagm commented on README.md
> +The purpose of the `lineage` object is to keep a record of the data processing history of the collection. Here the idea would be that each of process (vizzTool) returns a concise statement about an a
Isn't this quite overkill? What are the real use case for this need?

2020-10-20 18:24 UTC, aagm commented on README.md
> +And thats it! We have now pre-processed the dataset using a number of standardized tools, added it to our remote storage solution, and made the configuration available in our favorite API. Time to ta
I'm a bit skeptical of this, I see a lot of narrow cases happening. How are we going to handle long process, how are we going to handle failures in a graceful way, how are we going to handle credential on different services and providers.? I do like the idea on generating the payload on a specific API, but I'm not sure who is going to pay for the dev of each one( should we charge the projects? How should we define when we should develop a specific  api Payload?

2020-10-20 18:39 UTC, fgassert commented
Hi Ed,
Thanks for taking a crack at this. I have no objections in principle, but am struggling in how to review.

1. I see what you've defined here mostly as metadata, which aligns with common standards. This is good but also raises questions:
 - How is this metadata generated? Is it essential to input certain types of metadata to use Vizztools?
 - Should we aim to have our applications code and data models align with these properties? Is this mostly for internal data management?

2. Looking at @aagm's comments and in general at our proposal document, I think we still have not come to consensus about the problems we need a library to solve. In this case I think its particularly difficult to start at the abstract level, when our specific experiences and ways of working differ across team members. Can we identify the lowest common denominator of shared challenges, start from there, and grow outward? Perhaps if the Research team has free capacity we can ask them to help us define these questions and objectives.

2020-10-20 19:30 UTC, edwardpmorris commented on README.md
> +The Collection object stores information about a dataset, a collection of data items.  The actual data items can be in in a variety of formats. The general aim is not too actually store any data, but
My understanding was that `pygeoapi` is an implementation of  [OGC API standards](https://ogcapi.ogc.org/). But true better to say directly.

2020-10-20 20:32 UTC, edwardpmorris commented on README.md
> +Below is the basic top-level structure of a `Collection` object, which uses [JSON-LD](https://json-ld.org/) to provide context on the meaning of each property i.e., to find our the definition of a pr
JSON-LD allows the flexible linking of the definition of properties to defined vocabs/schema. This can help to reduce ambiguity (think of it as self-describing linked documentation within the data structure). Otherwise it behaves exactly like plain JSON. In terms of the purpose of `vizzToolsCore` to facilitate standardized data exchange, I see the advantage of aiding package developers to define and reuse properties and objects. In terms of cost, i do not directly see much difference; the documentation has to be written somewhere, seems better reuse or write it once and link it many times?

2020-10-20 21:23 UTC, edwardpmorris commented on README.md
> +> DISCUSS: Collection or Dataset?  In OGC circles collection seems to be the standard. "A collection of things". Dataset = "A collection of data items".
Yeah seems to a general area of [debate](https://github.com/opengeospatial/oapi_common/issues/111), undecided. OGC API and STAC seem to use `Collection`.

2020-10-20 21:44 UTC, edwardpmorris commented on README.md
> +A list of Provider configuration objects, which follow the structure of `pygeoapi` [resources.providers configuration](https://docs.pygeoapi.io/en/latest/configuration.html#resources). The aim of pro
Basically the proposal is to use most of the `pygeoapi` `Collection` object and EXACTLY the `pygeoapi` `resources.providers`.

2020-10-20 21:56 UTC, edwardpmorris commented on README.md
> +The purpose of the `lineage` object is to keep a record of the data processing history of the collection. Here the idea would be that each of process (vizzTool) returns a concise statement about an a
Happy to put this on low priority, it does seem relatively easy though? Add comments after major processing tasks. The use case is being able to give a short clear outline of what and when transformations were made to datasets (without looking through processing code).

For example, WDPA is download and transformed by wdpaTool version 0.1, by user X creating wdpa version "2018-09-30", it turns out user Y, fixes some errors in wdpaTool version 0.1, upgrading the processing code to version 0.2, they rerun the dataset processing, updating the wdpa version "2018-09-30" data files. User Z, checks `lineage` and sees the dataset is correctly updated using wdpaTool version 0.2, and can contact user Y if they would like confirmation.

2020-10-20 22:21 UTC, edwardpmorris commented on README.md
> +And thats it! We have now pre-processed the dataset using a number of standardized tools, added it to our remote storage solution, and made the configuration available in our favorite API. Time to ta
Think of it as an agreement for how we will work together and share. The scope of vizzToolsCore is only about agreeing on a minimum set of standard data structures to help interoperability between the various vizzTools (and services). Indeed, solving the issues above sounds like the seed for a fantastic `vizzToolsIO` package. We have LMIPy which deals with the RW API, for other APIs I would suggest "provider connection drivers" are generally done on a need basis; remember the idea is to make a better frame-work reuse of project code. If a more generic mechanism can be found then great. There are some specific python projects focusing on this, if we can use those even better!

2020-10-20 22:56 UTC, edwardpmorris commented
I have a strong desire to nudge us towards including more metadata, and ensuring this metadata is reused though-out the whole workflow. Still flexibility is also important.

> @fgassert How is this metadata generated? Is it essential to input certain types of metadata to use Vizztools?

1 machine-readable online resources, 2) a web-form filled in by the provider, 3) by the vizz-scientist preparing the data. The proposal is to use schema.org Dataset in general following the Google Dataset guidelines. The required/permitted status is to be decided (in the JSON schema). I am in favor of a minimum of `name` and `description`.

> @fgassert Should we aim to have our applications code and data models align with these properties? Is this mostly for internal data management?

I would say flexibility of how we do stuff internally in packages is important, on the other hand imagine we will all be fixing issues in tools that we are unfamiliar with, so some alignment could help. I think it is generally reasonable to require that any input or output for a tool MUST be in a standard data model (we can add data models as needed?). Mostly internal, but would like to use these tools in services too (reuse code, one source of truth).  

2. Yeah `vizzToolsCore` aims is provide a standardized set of data structures to facilitate inter-change between various specific vizzTools data processing packages.", this is basically a proposal to work on this consensus.

2020-10-21 20:25 UTC, fgassert commented
I think I understand better what you are proposing. This is different from how I'm used to working with data, so let me know if this is correct:

 - `Dataset`s are an *interface* for documenting and interacting with remote resources. You define a dateset with its origin and format information rather than from the data itself. 
 - The primary purpose of a `Dataset` is to easily maintain metadata and traceability across services. Dataset methods wrap transformations of metadata along with IO operations.
 - `Dataset` methods parse and create `JSON-LD`, similarly we should get used to reading/writing `JSON-LD` to manage datasets (or create methods for abstracting this).
 - The `Dataset` is agnostic to the type or format of the data. So the results of `io.get(ds).unpack()` is an object referencing one or more files which may be in multiple formats.
 - `io.export` in your example manages the metadata, rather than the data itself. The data first has to be uploaded to GEE (in this stop we create `provider` metadata). Then the `io.export` saves this metadata along with the reference to this provider in the RW API or as a json object in cloud storage.

2020-10-22 10:58 UTC, edwardpmorris commented
Thanks for the feedback and the nice summary. Yes, I think that is basically what i am proposing. I did not make too many assumptions about the the functionality of the tools, the psuedo-code was just to frame the idea.

I think these are the key concept:
>  Datasets are an interface for documenting and interacting with (remote) resources.

2020-10-22 13:55 UTC, fgassert commented
Great, yeah this makes sense to me then

2020-10-23 09:42 UTC, aagm approved these changes

2020-10-26 11:23 UTC, 01painadam approved these changes
Ok, in the interest of momentum - lets merge this PR but any remaining/open questions can be converted to Issues to be discussed down the line.

2020-10-26 12:18 UTC, merged